[package]
name = "markdown_webassembly_rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
comrak = { version = "0.28.0", features = ["syntect"] }
wasm-bindgen = "0.2.93"
console_error_panic_hook = "0.1.7"

[build-dependencies]
syntect = "5.2.0"
