[env]
TARGET_TYPE = "bundler"
RELEASE_TYPE = "dev"

[tasks.build-development]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = ["-V"] }
env = { TARGET_TYPE = "web" }
command = "wasm-pack"
args = [
    "build",
    "--target", "${TARGET_TYPE}",
    "--out-dir", "test_website/lib",
    "--${RELEASE_TYPE}"
]

[tasks.build-production]
extend = "build-development"
env = { RELEASE_TYPE = "release" }
args = [
    "build",
    "--target", "${TARGET_TYPE}",
    "--${RELEASE_TYPE}"
]

# Default to development build
[tasks.build]
clear = true
run_task = [
    { name = "build-production", condition = { profiles = ["production"] } },
    { name = "build-development" },
]