[tasks.build-development]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = ["-V"] }
command = "wasm-pack"
args = [
    "build",
    "--target", "web",
    "--out-dir", "test_website/lib",
    "--dev"
]

[tasks.build-production]
extend = "build-development"
args = [
    "build",
    "--target", "web",
    "--out-dir", "out",
    "--release"
] # Default to development build

# Default to development build
[tasks.build]
clear = true
run_task = [
    { name = "build-production", condition = { profiles = ["production"] } },
    { name = "build-development" },
]