name: Publish Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache cargo packages
      id: cache-cargo
      uses: actions/cache@v4
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo


    - name: Download cargo packages
      if: steps.cache-cargo.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-make
        cargo install wasm-pack

    - name: Build
      run: cargo make -p production

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        artifacts: 'out/markdown_webassembly_rs.*'
        commit: ${{ github.ref }}
        draft: true
        generateReleaseNotes: true
