name: Publish Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download cargo-make
      run: wget https://github.com/sagiegurari/cargo-make/releases/download/0.37.16/cargo-make-v0.37.16-x86_64-unknown-linux-gnu.zip -O cargo-make
    - name: Unzip cargo-make
      run: unzip cargo-make
    - name: Build
      run: ./cargo-make-v0.37.16-x86_64-unknown-linux-gnu/makers -p production
