name: Publish Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Cargo-Make
      run: cargo install --force cargo-make
    - name: Build
      run: cargo make -p production
